{% set version = "3.101" %}

package:
  name: lame
  version: "{{ version }}"

source:
  url: https://downloads.sourceforge.net/sourceforge/lame/lame-{{ version }}.tar.gz
  sha256: 7578af6eebd578b2bd64e468fac4ae1f03670a7e028166e67f855674b9b6aeac
  patches:
    - fixup_windows_build.patch

build:
  number: 0
  run_exports:
    # seems to be minor version compatibility
    # https://abi-laboratory.pro/tracker/timeline/lame/
    - {{ pin_subpackage('lame', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - make  # [unix]
    - nasm  # [win]

test:
  commands:
    - lame --genre-list testcase.mp3
    - lame --longhelp
    - test -f $PREFIX/include/lame/lame.h  # [not win]
    - if not exist %PREFIX%\\Library\\include\\lame\\lame.h exit 1  # [win]

about:
  home: https://lame.sourceforge.io/
  license: LGPL-2.0-only
  license_family: LGPL
  license_file: COPYING
  summary: 'High quality MPEG Audio Layer III (MP3) encoder'

  # The remaining entries in this section are optional, but recommended
  description: |
    LAME is a high quality MPEG Audio Layer III (MP3) encoder licensed under the LGPL.
    Today, LAME is considered the best MP3 encoder at mid-high bitrates and at VBR, mostly
    thanks to the dedicated work of its developers and the open source licensing model
    that allowed the project to tap into engineering resources from all around the world.
  doc_url: http://lame.sourceforge.net/using.php
  dev_url: https://svn.code.sf.net/p/lame/svn/trunk/lame/

extra:
  recipe-maintainers:
    - soumith
    - hmaarrfk
    - bmcfee
